### ISSUE TITLE
Using k8s credentials handling the library throws an exception

### ISSUE THREAD

**Issue by zmeda** [zalando/tokens#78] opened 2017-03-23 13:25 UTC
The first time tokens are used after k8s pod is created the library fails with exception:

    org.zalando.stups.tokens.AccessTokenUnavailableException: no token available
	    at org.zalando.stups.tokens.AbstractAccessTokenRefresher.getAccessToken(AbstractAccessTokenRefresher.java:83) ~[org.zalando.stups.tokens-0.11.0-beta-2.jar:na]
	    at org.zalando.stups.tokens.AbstractAccessTokenRefresher.get(AbstractAccessTokenRefresher.java:76) ~[org.zalando.stups.tokens-0.11.0-beta-2.jar:na]

The way we are using the library in our service is:

    AccessTokens tokens = Tokens
      .createAccessTokensWithUri(new URI(config.getString("accessToken.url")))
      .manageToken("my-token")
      .addScope("uid")
      .done()
      .start()
    /*...*/
    tokens.get("my-token")

The failure happens **only for the first time**. Every time after first usage we are using `tokens.get...` it works.

**Comment by jbellmann** [comment] 2017-05-08 07:37
Thanks for reporting this. Currently I have no idea, why this happens. I will investigate some time in the next days.

**Comment by jbellmann** [comment] 2017-05-22 16:00
@zmeda 

I'm unable to reproduce this error. If you can show me how you use the library please contact me.

Close this now. Please reopen, if you still experience this issue.

Regards
Jörg

**Closed by jbellmann** 2017-05-22 16:00 UTC
